### ISSUE TITLE
[Req]: Use `husky` and `lint-staged` to lint files on every commit

### ISSUE THREAD

**Issue by gaston-flores** [developertools-tech/developertools.tech#56]
### Explain the proposed feature

Not exactly a feature, more of a nice-to-have for the repo. We can configure [git hooks](https://github.com/typicode/husky) to trigger [lint-staged](https://github.com/okonet/lint-staged) on every commit, which in turn would run eslint and prettier on the staged files. This should give more immediate feedback to the developer on the changes they are committing. As an added plus they won't need to remember to run `cq` on every push to the repo.

As an aside, I'd also suggest removing `eslint-plugin-prettier` and running `prettier` as a separate command. Using this plugin is [discouraged by prettier themselves](https://prettier.io/docs/en/integrating-with-linters.html#notes) and on a more personal note, I find it a bit distracting (your mileage may vary).

Looking forward to your feedback!

#### Requirements

- [x] Install husky + lint-staged
- [x] Separate prettier from eslint
- [x] Add prettier to `cq:ci`
- [x] Update CONTRIBUTING.md and the PR template to reflect these changes

**Comment by dlford** [comment]
@gaston-flores 

I've used husky and lint-staged before and I think it would help keep the PR's cleaner, so I'm on board.

I didn't know about the `eslint-plugin-prettier` discouragement, thanks for sharing that, I think it's a sound argument and agree with you there too.

We would also have to add a `prettier:ci` script that doesn't modify the files, and include that in the `cq:ci` script. I'm sure you'd have seen that need but it doesn't hurt to be specific.

The only thing missing is `tsc --noEmit`, which I added to the `cq` script because there are some TypeScript errors that eslint doesn't catch, but I suppose that could be run with husky too.

Also, I think we could let tests run on GitHub actions instead of in contributor land (currently running in both), they are starting to get more time consuming and I don't see a need to run them twice.

Lastly, we would also need to adjust the `CONTRIBUTING.md` file accordingly.

This one's all yours if you want it?

**Comment by dlford** [comment]
Oh, and the PR template mentions the `cq` script too, forgot about that

**Comment by gaston-flores** [comment]
Great! Agreed on all points 🚀

**Comment by dlford** [comment]
@gaston-flores thank you!
